- hosts: localhost
  tasks:
  - package:
      name: httpd
      state: present
  - copy:
      content: "<body bgcolor = red><h1 align = center>This is a Test.</h1>"
      dest: /var/www/html/index.html
    notify:
    - Restart apache
  - service:
      name: httpd
      enabled: yes
      state: started
  - service:
       name: Restart apache
       service:
          name: httpd
          state: restarted
       
